<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="homeplater">
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    <material name="purple">
        <color rgba="0.3098 0.1765 0.4980 1" />
    </material>
    <material name="gray">
        <color rgba="0.5 0.5 0.5 1" />
    </material>

    <!-- base properties -->
    <xacro:property name="base_depth" value="0.16" />
    <xacro:property name="base_width" value="0.16" />
    <xacro:property name="base_height" value="0.005" />
    <!-- wheel properties -->
    <xacro:property name="wheel_xoffset" value="0.048" />
    <xacro:property name="wheel_yoffset" value="0.095" />
    <xacro:property name="wheel_zoffset" value="-0.013" />
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_width" value="0.027" />
    <!-- caster properties -->
    <xacro:property name="caster_xoffset" value="-0.044" />
    <!-- <xacro:property name="caster_zoffset" value="-0.0315" /> -->
    <xacro:property name="caster_radius" value="0.014" />
    <xacro:property name="caster_mass" value="0.1" />

    <!-- Wheel macro -->
    <xacro:macro name="wheel" params="prefix y_reflect">
        <joint name="${prefix}_joint" type="continuous">
            <parent link="base_link" />
            <child link="${prefix}_link" />
            <origin xyz="${wheel_xoffset} ${y_reflect*wheel_yoffset} ${wheel_zoffset}" rpy="${pi/2} 0 0" />
            <axis xyz="0 0 1" />
        </joint>

        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}" />
                </geometry>
                <material name="black" />
            </visual>
        </link>
    </xacro:macro>

    <!-- BASE -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_depth} ${base_width} ${base_height}"/>
            </geometry>
            <material name="purple"/>
        </visual>
    </link>

    <joint name="caster_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster" />
        <origin xyz="${caster_xoffset} 0.0 ${caster_radius-wheel_radius+wheel_zoffset}" />
    </joint>

    <!-- CASTER WHEEL -->
    <link name="caster">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}" />
            </geometry>
            <material name="gray" />
        </visual>
    </link>

    <!-- LEFT AND RIGHT WHEEL -->
    <xacro:wheel prefix="left_wheel" y_reflect="1" />
    <xacro:wheel prefix="right_wheel" y_reflect="-1" />
    
</robot>
