<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <!-- <xacro:include filename="$(find hpr_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find hpr_description)/urdf/inertia.xacro" /> -->
    <xacro:include filename="materials.xacro" />
    <xacro:include filename="inertia.xacro" />

    <!-- base properties -->
    <xacro:property name="chassis_xoffset" value="-0.048" />
    <xacro:property name="chassis_zoffset" value="0.013" />
    <xacro:property name="chassis_depth" value="0.16" />
    <xacro:property name="chassis_width" value="0.16" />
    <xacro:property name="chassis_height" value="0.005" />
    <xacro:property name="chassis_mass" value="0.2" />
    <!-- wheel properties -->
    <xacro:property name="wheel_yoffset" value="0.095" />
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_width" value="0.027" />
    <xacro:property name="wheel_mass" value="0.032" />
    <!-- caster properties -->
    <xacro:property name="caster_xoffset" value="-0.092" />
    <xacro:property name="caster_radius" value="0.014" />
    <xacro:property name="caster_mass" value="0.05" />
    <!-- lidar properties -->
    <xacro:property name="lidar_radius" value="0.035" />
    <xacro:property name="lidar_height" value="0.02" />
    <xacro:property name="lidar_zoff" value="0.08" />
    <xacro:property name="lidar_mass" value="0.17" />

    <!-- Wheel macro -->
    <xacro:macro name="wheel" params="prefix y_reflect">
        <joint name="${prefix}_joint" type="continuous">
            <parent link="base_link" />
            <child link="${prefix}_link" />
            <origin xyz="0 ${y_reflect*wheel_yoffset} 0" rpy="${-pi/2} 0 0" />
            <axis xyz="0 0 1" />
        </joint>

        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}" />
                </geometry>
                <material name="black" />
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}" />
                </geometry>
            </collision>

            <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}" />

        </link>

        <gazebo reference="${prefix}_link">
            <material>Gazebo/Black</material>
        </gazebo>    
    </xacro:macro>

    <!-- DUMMY BASE -->
    <link name="base_link">
    </link>

    <!-- CHASSIS -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis_link" />
        <origin xyz="${chassis_xoffset} 0 ${chassis_zoffset}" />
    </joint>

    <link name="chassis_link">
        <visual>
            <geometry>
                <box size="${chassis_depth} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="purple"/>
        </visual>

        <collision>
            <geometry>
                <box size="${chassis_depth} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>

        <xacro:box_inertia m="${chassis_mass}" x="${chassis_depth}" y="${chassis_width}" z="${chassis_height}" />
    </link>

    <gazebo reference="chassis_link">
        <material>Gazebo/Purple</material>
    </gazebo>

<<<<<<< HEAD
    <!-- CASTER WHEEL -->
    <joint name="caster_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_link" />
        <origin xyz="${caster_xoffset} 0.0 ${caster_radius-wheel_radius}" />
    </joint>

=======
    <!-- FOOTPRINT -->
    <joint name="footprint_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
        <origin xyz="${chassis_xoffset} 0 ${-wheel_radius}" />
    </joint>

    <link name="base_footprint">
    </link>

    <!-- CASTER WHEEL -->
    <joint name="caster_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_link" />
        <origin xyz="${caster_xoffset} 0.0 ${caster_radius-wheel_radius}" />
    </joint>

>>>>>>> 7-sim_slam
    <link name="caster_link">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}" />
            </geometry>
            <material name="gray" />
        </visual>

        <collision>
            <geometry>
                <sphere radius="${caster_radius}" />
            </geometry>
        </collision>

        <xacro:sphere_inertia m="${caster_mass}" r="${caster_radius}" />
    </link>

    <gazebo reference="caster_link">
        <mu1>0.00000001</mu1>
        <mu2>0.00000001</mu2>
        <material>Gazebo/Gray</material>
    </gazebo>

    <!-- LEFT AND RIGHT WHEEL -->
    <xacro:wheel prefix="left_wheel" y_reflect="1" />
    <xacro:wheel prefix="right_wheel" y_reflect="-1" />
    
</robot>
